### ISSUE TITLE
中文支持可以帮忙看下不  英文路径可以成功

### ISSUE THREAD

**Issue by Johnnychentong** [Arjen10/geoserver-manager#2]
![image](https://github.com/Arjen10/geoserver-manager/assets/51221680/675ceeab-d8b0-43fd-95f2-c754c8693773)
大概到这就出问题了  引文路径这一步就不为空
![image](https://github.com/Arjen10/geoserver-manager/assets/51221680/70e7a42f-d68f-4936-8386-e0f8262e20bc)

**Comment by Johnnychentong** [comment]
![image](https://github.com/Arjen10/geoserver-manager/assets/51221680/f23aafb3-9620-46e3-9c69-026740c8977d)
在这一步状态码500    zip里面的文件是中文

**Comment by Arjen10** [comment]
确保你的shp压缩包的名称跟shp文件名称一致，且shp压缩包里面不要出现文件夹目录，压缩包打开就是shp文件

**Comment by Arjen10** [comment]
1. 确保你的shp压缩包的名称跟shp文件名称一致，且shp压缩包里面不要出现文件夹目录，压缩包打开就是shp文件
2. 通过返回的url我猜测，你的压缩包应该是英文的，而shp文件又是中文的。这种情况只要你的压缩包文件名称和shp文件名称不一致应该都不会发布成功

**Comment by Johnnychentong** [comment]
这个解决了  应该是本地中文编码上传到服务器解压失败了  把文件传到服务器再去发布就没问题了  谢谢笑川哥

**Comment by Arjen10** [comment]
> 这个解决了 应该是本地中文编码上传到服务器解压失败了 把文件传到服务器再去发布就没问题了 谢谢笑川哥

对，会有编码问题。不用谢
